name       : xdpyinfo
version    : 1.3.3
release    : 9
source     :
    - https://xorg.freedesktop.org/archive/individual/app/xdpyinfo-1.3.3.tar.gz : 2ae7b8213ea839b8376843477496276e8d69550c48bff081e16376539fc27c5a
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications - xdpyinfo
description: |
    X.Org Applications - xdpyinfo
builddeps  :
    - pkgconfig(dmx)
    - pkgconfig(x11-xcb)
    - pkgconfig(xproto)
    - pkgconfig(xcomposite)
    - pkgconfig(xinerama)
    - pkgconfig(xtst)
    - pkgconfig(xrender)
    - pkgconfig(xxf86dga)
    - pkgconfig(xxf86vm)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
