name       : xdpyinfo
version    : 1.3.2
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xdpyinfo-1.3.2.tar.bz2 : 30238ed915619e06ceb41721e5f747d67320555cc38d459e954839c189ccaf51
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications - xdpyinfo
description: |
    X.Org Applications - xdpyinfo
builddeps  :
    - pkgconfig(dmx)
    - pkgconfig(x11-xcb)
    - pkgconfig(xproto)
    - pkgconfig(xcomposite)
    - pkgconfig(xinerama)
    - pkgconfig(xtst)
    - pkgconfig(xrender)
    - pkgconfig(xxf86dga)
    - pkgconfig(xxf86vm)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
